trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'Azure-Yousma-Connection'
  acrLoginServer: 'myprojectacr1234.azurecr.io'
  imageName: 'moodly'
  imageTag: 'latest'

stages:
  # ----------------------------------------------
  # CI Stage: Build Docker Image
  # ----------------------------------------------
  - stage: CI
    displayName: 'Build Docker Image'
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - script: |
              echo "🐳 Docker Diagnostics"
              docker version
              docker info
            displayName: 'Docker Info'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              repository: $(imageName)
              dockerfile: backend/Dockerfile
              buildContext: backend
              tags: $(imageTag)

          - script: |
              docker save -o $(Build.ArtifactStagingDirectory)/$(imageName).tar $(imageName):$(imageTag)
            displayName: 'Save Docker Image to Tar'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Docker Image Artifact'
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifact: 'docker-image'

  # ----------------------------------------------
  # CD Stage: Deploy Infra, Push Image & Deploy App
  # ----------------------------------------------
  - stage: CD
    displayName: 'Deploy Infra, Push Image & Deploy App'
    dependsOn: CI
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: DownloadPipelineArtifact@2
            displayName: 'Download Docker Image Artifact'
            inputs:
              artifact: 'docker-image'
              path: $(Build.ArtifactStagingDirectory)

          - script: |
              docker load -i $(Build.ArtifactStagingDirectory)/$(imageName).tar
            displayName: 'Load Docker Image from Tar'

          - task: TerraformInstaller@1
            displayName: 'Install Terraform 1.6.6'
            inputs:
              terraformVersion: '1.6.6'

          - task: TerraformTaskV4@4
            name: TerraformInit
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: init
              workingDirectory: terraform
              backendServiceArm: $(azureSubscription)
              backendAzureRmResourceGroupName: yousma-rg
              backendAzureRmStorageAccountName: yousmastorage
              backendAzureRmContainerName: tfstate
              backendAzureRmKey: terraform.tfstate
              environmentServiceNameAzureRM: $(azureSubscription)
              commandOptions: -upgrade

          # Apply Infra only (ACR first)
          - task: TerraformTaskV4@4
            name: TerraformApplyInfra
            displayName: 'Terraform Apply - Infra Only (creates ACR)'
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: terraform
              environmentServiceNameAzureRM: $(azureSubscription)
              commandOptions: >
                -target=azurerm_container_registry.acr
                -var="email_api_key=$(EMAIL_API_KEY)"
                -auto-approve

          - task: AzureCLI@2
            displayName: 'Docker Login to ACR'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az acr login --name myprojectacr1234

          - script: |
              docker tag $(imageName):$(imageTag) $(acrLoginServer)/$(imageName):$(imageTag)
            displayName: 'Tag Docker Image for ACR'

          - task: Docker@2
            displayName: 'Push Docker Image to ACR'
            inputs:
              command: push
              repository: $(acrLoginServer)/$(imageName)
              tags: $(imageTag)

          - task: TerraformTaskV4@4
            displayName: 'Terraform Apply - All remaining resources'
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: terraform
              environmentServiceNameAzureRM: $(azureSubscription)
              commandOptions: >
                -var="email_api_key=$(EMAIL_API_KEY)"
                -auto-approve

          - task: AzureCLI@2
            displayName: 'Show Terraform output (app_url)'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Terraform outputs:"
                terraform -chdir=terraform output || true
