trigger:
  branches:
    include:
      - main

variables:
  - group: Azurecredentials
  - name: acrName
    value: 'contactsaveracr1234'
  - name: containerImage
    value: 'contact-saver'
  - name: dockerfilePath
    value: 'backend'
  - name: tfBackendRg
    value: 'yousma-rg'
  - name: tfStorage
    value: 'yousmastorage'
  - name: tfContainer
    value: 'tfstate'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image to ACR
    jobs:
      - job: Build
        timeoutInMinutes: 20
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: Build and Push
            inputs:
              containerRegistry: 'acr-connection1'
              repository: '$(containerImage)'
              command: 'buildAndPush'
              Dockerfile: '$(dockerfilePath)/Dockerfile'
              buildContext: '$(dockerfilePath)'
              tags: |
                latest

  - stage: Deploy
    displayName: Deploy Infrastructure and App
    dependsOn: BuildAndPush
    jobs:
      - job: TerraformDeploy
        displayName: Terraform Deploy Infra and WebApp
        timeoutInMinutes: 40
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: '1.6.6'

          - task: TerraformCLI@0
            displayName: Terraform Init
            inputs:
              command: init
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendType: azurerm
              backendServiceArm: 'Azure-Yousma-Connection'
              ensureBackend: true
              backendAzureRmResourceGroupName: '$(tfBackendRg)'
              backendAzureRmStorageAccountName: '$(tfStorage)'
              backendAzureRmContainerName: '$(tfContainer)'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformCLI@0
            displayName: Terraform Plan
            inputs:
              command: plan
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceName: 'Azure-Yousma-Connection'
              vars: |
                resource_group_name=$(tfBackendRg)
                location=East US
                acr_name=$(acrName)
                web_app_name=contact-saver-app
                key_vault_name=yousma-kv
                email_api_key=$(email_api_key)
                acr_admin_username=$(acr_admin_username)
                acr_admin_password=$(acr_admin_password)
                container_image=$(containerImage)
                app_service_plan_name=contact-plan

          - task: TerraformCLI@0
            displayName: Terraform Apply
            inputs:
              command: apply
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceName: 'Azure-Yousma-Connection'
              vars: |
                resource_group_name=$(tfBackendRg)
                location=East US
                acr_name=$(acrName)
                web_app_name=contact-saver-app
                key_vault_name=yousma-kv
                email_api_key=$(email_api_key)
                acr_admin_username=$(acr_admin_username)
                acr_admin_password=$(acr_admin_password)
                container_image=$(containerImage)
                app_service_plan_name=contact-plan
              commandOptions: '-auto-approve'
