trigger:
  branches:
    include:
      - main

variables:
  - group: Azurecredentials   # ✅ Correctly nested
  - name: acrName
    value: 'contactsaveracr123'
  - name: containerImage
    value: 'contact-saver'
  - name: dockerfilePath
    value: 'backend/Dockerfile'
  - name: tfBackendRg
    value: 'yousma-rg'
  - name: tfStorage
    value: 'yousmastorage'
  - name: tfContainer
    value: 'tfstate'
  - name: tfKey
    value: 'terraform.tfstate'
  - name: webAppName
    value: 'contact-webapp-123'
  - name: keyVaultName
    value: 'contactkv123'
  - name: location
    value: 'East US'
  - name: app_service_plan_name
    value: 'contact-asp'
  - name: email_api_key
    value: 'sample-api-key'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
    - job: BuildImage
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: Docker@2
          displayName: 'Build and Push to ACR'
          inputs:
            containerRegistry: 'acr-connection'
            repository: $(containerImage)
            command: buildAndPush
            Dockerfile: $(dockerfilePath)
            tags: |
              latest

- stage: Deploy
  displayName: 'Deploy Terraform Infrastructure'
  dependsOn: Build
  jobs:
    - job: Terraform
      displayName: 'Run Terraform with Env Auth'
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: TerraformInstaller@0
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: '1.7.5'

        - script: |
            echo "Setting environment variables"
            export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
            export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
            export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
            export ARM_TENANT_ID=$(ARM_TENANT_ID)

            cd terraform
            terraform init \
              -backend-config="resource_group_name=$(tfBackendRg)" \
              -backend-config="storage_account_name=$(tfStorage)" \
              -backend-config="container_name=$(tfContainer)" \
              -backend-config="key=$(tfKey)"

            echo "Fetching ACR credentials..."
            ACR_USERNAME=$(az acr credential show --name $(acrName) --query "username" -o tsv)
            ACR_PASSWORD=$(az acr credential show --name $(acrName) --query "passwords[0].value" -o tsv)

            echo "Running Terraform apply..."
            terraform apply \
              -var="resource_group_name=$(tfBackendRg)" \
              -var="location=$(location)" \
              -var="acr_name=$(acrName)" \
              -var="app_service_plan_name=$(app_service_plan_name)" \
              -var="web_app_name=$(webAppName)" \
              -var="key_vault_name=$(keyVaultName)" \
              -var="email_api_key=$(email_api_key)" \
              -var="acr_admin_username=$ACR_USERNAME" \
              -var="acr_admin_password=$ACR_PASSWORD" \
              -var="container_image=$(containerImage)" \
              -auto-approve
          displayName: 'Run Terraform Init and Apply'
