trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'Azure-Yousma-Connection'  # ✅ Your ARM connection
  containerRegistry: 'acr-connection1'          # ✅ Your Docker registry connection
  acrLoginServer: 'myprojectacr1234.azurecr.io'
  imageName: 'myapp'

stages:
- stage: CI
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: '$(imageName)'
        dockerfile: 'backend/Dockerfile'
        containerRegistry: '$(containerRegistry)'  # ✅ Use service connection here
        tags: |
          latest

- stage: CD
  displayName: 'Deploy Infra & App via Terraform'
  dependsOn: CI
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      name: TerraformInit
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'terraform'
        environmentServiceNameAzureRM: '$(azureSubscription)'

    - task: TerraformTaskV4@4
      name: TerraformApply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'terraform'
        environmentServiceNameAzureRM: '$(azureSubscription)'
