trigger:
  branches:
    include:
      - main

variables:
  imageName: contact-saver

stages:
- stage: Build
  displayName: Build & Push Image to ACR
  jobs:
    - job: BuildImage
      displayName: Build & Push
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'acr-connection1'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az acr login --name $(acr_name)
              docker build -t $(acr_name).azurecr.io/$(imageName):latest .
              docker push $(acr_name).azurecr.io/$(imageName):latest

- stage: Deploy
  displayName: Terraform Infra Deploy
  dependsOn: Build
  jobs:
    - job: TerraformApply
      displayName: Apply Infrastructure
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'acr-connection1'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
              export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
              export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
              export ARM_TENANT_ID=$(ARM_TENANT_ID)

              cd terraform
              terraform init
              terraform import azurerm_container_registry.acr "/subscriptions/$(ARM_SUBSCRIPTION_ID)/resourceGroups/yousma-rg/providers/Microsoft.ContainerRegistry/registries/$(acr_name)"
              terraform apply -auto-approve \
                -var="acr_name=$(acr_name)" \
                -var="email_api_key=$(email_api_key)" \
                -var="webapp_name=$(webapp_name)" \
                -var="app_service_plan_name=$(app_service_plan_name)" \
                -var="tenant_id=$(ARM_TENANT_ID)" \
                -var="acr_admin_username=$(acr_admin_username)" \
                -var="acr_admin_password=$(acr_admin_password)" \
                -var="image_name=$(imageName)" \
                -var="key_vault_name=$(keyVaultName)" \
                -var="resource_group_name=$(resource_group_name)" \
                -var="location=$(location)"
