trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'Azure-Yousma-Connection'
  acrName: 'myprojectacr1234'
  acrLoginServer: 'myprojectacr1234.azurecr.io'
  imageName: 'moodly'

stages:
# Step 1: Create RG + ACR
- stage: Create_ACR
  displayName: 'Terraform Apply - Create RG + ACR'
  jobs:
  - job: TF_ACR
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'
    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: init
        workingDirectory: terraform
        backendServiceArm: $(azureSubscription)
        backendAzureRmResourceGroupName: yousma-rg
        backendAzureRmStorageAccountName: yousmastorage
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: terraform.tfstate
        environmentServiceNameAzureRM: $(azureSubscription)
    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply - Only RG + ACR'
      inputs:
        provider: 'azurerm'
        command: apply
        workingDirectory: terraform
        environmentServiceNameAzureRM: $(azureSubscription)
        commandOptions: >
          -target=azurerm_resource_group.rg
          -target=azurerm_container_registry.acr
          -auto-approve

# Step 2: Build and Push Image
- stage: Build_Push
  displayName: 'Build & Push Docker Image'
  dependsOn: Create_ACR
  jobs:
  - job: BuildPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: 'Login to ACR & Push Image'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)
          IMAGE=$(acrLoginServer)/$(imageName):latest
          docker build -t $IMAGE backend
          docker push $IMAGE
    - task: AzureCLI@2
      displayName: 'Verify Image in ACR'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr repository list --name $(acrName) --output table
          az acr repository show-tags --name $(acrName) --repository $(imageName) --output table

# Step 3: Deploy Infra + App
- stage: Deploy_App
  displayName: 'Deploy Infra & App'
  dependsOn: Build_Push
  jobs:
  - job: TF_App
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'
    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: init
        workingDirectory: terraform
        backendServiceArm: $(azureSubscription)
        backendAzureRmResourceGroupName: yousma-rg
        backendAzureRmStorageAccountName: yousmastorage
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: terraform.tfstate
        environmentServiceNameAzureRM: $(azureSubscription)
    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply - All Remaining Infra + App'
      inputs:
        provider: 'azurerm'
        command: apply
        workingDirectory: terraform
        environmentServiceNameAzureRM: $(azureSubscription)
        commandOptions: -auto-approve
