trigger:
  branches:
    include:
      - main

variables:
  azureServiceConnection: 'Azure-Yousma-Connection'
  dockerRegistryServiceConnection: 'acr-connection'
  acrName: 'contactsaveracr123'
  containerImage: 'contact-saver'
  dockerfilePath: 'backend/Dockerfile'
  tfBackendRg: 'yousma-rg'                  # ✅ match the main.tf
  tfStorage: 'yousmastorage'                # ✅ match main.tf
  tfContainer: 'tfstate'                    # ✅ match main.tf
  tfKey: 'terraform.tfstate'

stages:

# ----------------------------------------
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
    - job: BuildImage
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: Docker@2
          displayName: 'Build and Push to ACR'
          inputs:
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(containerImage)
            command: buildAndPush
            Dockerfile: $(dockerfilePath)
            tags: |
              latest

# ----------------------------------------
- stage: Deploy
  displayName: 'Terraform Deploy Infra'
  dependsOn: Build
  jobs:
    - job: Terraform
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: TerraformInstaller@0
          inputs:
            terraformVersion: '1.7.5'

        - task: TerraformTaskV1@0
          displayName: 'Terraform Init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: 'terraform'
            backendServiceArm: $(azureServiceConnection)         # ✅ Only this needed
            backendAzureRmResourceGroupName: $(tfBackendRg)
            backendAzureRmStorageAccountName: $(tfStorage)
            backendAzureRmContainerName: $(tfContainer)
            backendAzureRmKey: $(tfKey)

        - task: TerraformTaskV1@0
          displayName: 'Terraform Apply'
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: 'terraform'
            environmentServiceNameAzureRM: $(azureServiceConnection)
            vars: |
              resource_group_name=yousma-rg
              location=East US
              acr_name=$(acrName)
              app_service_plan_name=contact-asp
              web_app_name=contact-webapp
              key_vault_name=contactkv
              email_api_key=sample-api-key
              acr_admin_username=$(ACR_USERNAME)
              acr_admin_password=$(ACR_PASSWORD)
              container_image=$(containerImage)
            args: '-auto-approve'
