trigger:
  branches:
    include:
      - main  # main branch

variables:
  - group: Azurecredentials
  - name: acrName
    value: 'contactsaveracr1234'
  - name: containerImage
    value: 'contact-saver'
  - name: dockerfilePath
    value: 'backend/Dockerfile'
  - name: tfBackendRg
    value: 'yousma-rg'
  - name: tfStorage
    value: 'yousmastorage'
  - name: tfContainer
    value: 'tfstate'
  - name: tfKey
    value: 'terraform.tfstate'
  - name: webAppName
    value: 'contact-webapp-123'
  - name: keyVaultName
    value: 'contactkv123'
  - name: location
    value: 'East US'
  - name: app_service_plan_name
    value: 'contact-asp'
  - name: email_api_key
    value: 'sample-api-key'

stages:

# ---------- 🔧 Build Docker Image ----------
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
    - job: BuildImage
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: Docker@2
          displayName: 'Build and Push to ACR'
          inputs:
            containerRegistry: 'acr-connection1'  # ✅ Docker Registry type
            repository: $(containerImage)
            command: buildAndPush
            Dockerfile: $(dockerfilePath)
            tags: |
              latest

# ---------- 🚀 Deploy Infrastructure ----------
- stage: Deploy
  displayName: 'Deploy Terraform Infrastructure'
  dependsOn: Build
  jobs:
    - job: Terraform
      displayName: 'Run Terraform'
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: TerraformInstaller@0
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: '1.7.5'

        - task: AzureCLI@2
          displayName: 'Terraform Init and Apply'
          inputs:
            azureSubscription: 'Azure-Yousma-Connection'  # ✅ AzureRM type
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              echo "Setting up environment..."
              cd terraform

              echo "Terraform Init..."
              terraform init \
                -backend-config="resource_group_name=$(tfBackendRg)" \
                -backend-config="storage_account_name=$(tfStorage)" \
                -backend-config="container_name=$(tfContainer)" \
                -backend-config="key=$(tfKey)"

              echo "Terraform Apply..."
              terraform apply \
                -var="resource_group_name=$(tfBackendRg)" \
                -var="location=$(location)" \
                -var="acr_name=$(acrName)" \
                -var="app_service_plan_name=$(app_service_plan_name)" \
                -var="web_app_name=$(webAppName)" \
                -var="key_vault_name=$(keyVaultName)" \
                -var="email_api_key=$(email_api_key)" \
                -var="acr_admin_username=$(acr_admin_username)" \
                -var="acr_admin_password=$(acr_admin_password)" \
                -var="container_image=$(containerImage)" \
                -auto-approve
