trigger:
  branches:
    include:
      - main

variables:
  - group: Azurecredentials
  - name: acrName
    value: 'contactsaveracr1234'
  - name: containerImage
    value: 'contact-saver'
  - name: dockerfilePath
    value: 'backend'
  - name: tfBackendRg
    value: 'yousma-rg'
  - name: tfStorage
    value: 'yousmastorage'
  - name: tfContainer
    value: 'tfstate'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image to ACR
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: Build and Push Docker Image
            inputs:
              containerRegistry: 'acr-connection1'
              repository: '$(containerImage)'
              command: 'buildAndPush'
              Dockerfile: '$(dockerfilePath)/Dockerfile'
              buildContext: '$(dockerfilePath)'
              tags: |
                latest

  - stage: Deploy
    displayName: Deploy Infra and Patch Image
    dependsOn: BuildAndPush
    jobs:
      - job: TerraformDeploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureKeyVault@2
            displayName: Fetch EMAIL-API-KEY
            inputs:
              azureSubscription: 'Azure-Yousma-Connection'
              KeyVaultName: 'contactkv123'
              SecretsFilter: 'EMAIL-API-KEY'
              RunAsPreJob: true

          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: '1.6.6'

          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure-Yousma-Connection'
              backendAzureRmResourceGroupName: '$(tfBackendRg)'
              backendAzureRmStorageAccountName: '$(tfStorage)'
              backendAzureRmContainerName: '$(tfContainer)'
              backendAzureRmKey: 'terraform.tfstate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

          # Stage 1 - Only Container App (with dummy image)
          - task: TerraformTaskV4@4
            displayName: Terraform Apply (Container App Infra)
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Azure-Yousma-Connection'
              commandOptions: '-auto-approve -target=azurerm_container_app.app'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              runAzLogin: true
              ensureBackend: true
              installTerraform: false
            env:
              TF_VAR_resource_group_name: $(tfBackendRg)
              TF_VAR_location: 'East US'
              TF_VAR_acr_name: $(acrName)
              TF_VAR_web_app_name: 'contact-saver-app'
              TF_VAR_key_vault_name: 'contactkv123'
              TF_VAR_email_api_key: $(EMAIL-API-KEY)
              TF_VAR_container_image: $(containerImage)

          # Stage 2 - Assign Role (after identity is created)
          - task: TerraformTaskV4@4
            displayName: Terraform Apply (ACR Pull Role)
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Azure-Yousma-Connection'
              commandOptions: '-auto-approve -target=azurerm_role_assignment.acr_pull'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              runAzLogin: true
              ensureBackend: true
              installTerraform: false
            env:
              TF_VAR_resource_group_name: $(tfBackendRg)
              TF_VAR_location: 'East US'
              TF_VAR_acr_name: $(acrName)
              TF_VAR_web_app_name: 'contact-saver-app'
              TF_VAR_key_vault_name: 'contactkv123'
              TF_VAR_email_api_key: $(EMAIL-API-KEY)
              TF_VAR_container_image: $(containerImage)

          # Stage 3 - Patch final image + secrets
          - task: TerraformTaskV4@4
            displayName: Terraform Apply (Patch Final Image)
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: '-auto-approve -target=azapi_update_resource.patch_container_app'
              environmentServiceNameAzureRM: 'Azure-Yousma-Connection'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              runAzLogin: true
              ensureBackend: true
              installTerraform: false
            env:
              TF_VAR_resource_group_name: $(tfBackendRg)
              TF_VAR_location: 'East US'
              TF_VAR_acr_name: $(acrName)
              TF_VAR_web_app_name: 'contact-saver-app'
              TF_VAR_key_vault_name: 'contactkv123'
              TF_VAR_email_api_key: $(EMAIL-API-KEY)
              TF_VAR_container_image: $(containerImage)
