trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'Azure-Yousma-Connection'      # ARM service connection name
  acrLoginServer: 'myprojectacr1234.azurecr.io'
  imageName: 'moodly'
  imageTag: 'latest'
  
stages:
  # ----------------------------------------------
  # ðŸ”¹ CI Stage: Build Docker Image
  # -----------------------------------------------
  - stage: CI
    displayName: 'Build Docker Image'
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - script: |
              echo "ðŸ³ Docker Diagnostics"
              docker version
              docker info
            displayName: 'Docker Info'
            
          # âœ… Build the Docker image, but don't push it yet.
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              containerRegistry: ''  # No registry connection needed for build
              repository: $(imageName)
              dockerfile: backend/Dockerfile
              buildContext: backend
              tags: $(imageTag)
              
          # âœ… Publish the image as an artifact for the next stage
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Docker Image Artifact'
            inputs:
              targetPath: $(Build.SourcesDirectory) # Path to the Docker image
              artifact: 'docker-image'
              publishLocation: 'pipeline'



  # --------------------------------------------------------
  # ðŸ”¹ CD Stage: Deploy Infrastructure, then Push Image and Deploy App
  # --------------------------------------------------------
  - stage: CD
    displayName: 'Deploy Infra, Push Image & Deploy App'
    dependsOn: CI
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          # âœ… Download the Docker image artifact from the CI stage
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Docker Image Artifact'
            inputs:
              artifact: 'docker-image'
              path: $(Build.SourcesDirectory)

          # âœ… Install Terraform and run Init/Apply for infrastructure
          - task: TerraformInstaller@1
            displayName: 'Install Terraform 1.6.6'
            inputs:
              terraformVersion: '1.6.6'

          - task: TerraformTaskV4@4
            name: TerraformInit
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: init
              workingDirectory: terraform
              backendServiceArm: $(azureSubscription)
              backendAzureRmResourceGroupName: yousma-rg
              backendAzureRmStorageAccountName: yousmastorage
              backendAzureRmContainerName: tfstate
              backendAzureRmKey: terraform.tfstate
              environmentServiceNameAzureRM: $(azureSubscription)
              commandOptions: -upgrade

          - task: TerraformTaskV4@4
            name: TerraformApplyInfra
            displayName: 'Terraform Apply - Infra Only (creates ACR)'
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: terraform
              environmentServiceNameAzureRM: $(azureSubscription)
              commandOptions: >
                -target=azurerm_container_registry.acr
                -var="email_api_key=$(EMAIL_API_KEY)"
                -auto-approve

          # âœ… Login to the newly created ACR
          - task: AzureCLI@2
            displayName: 'Docker Login to ACR'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az acr login --name myprojectacr1234
                
          # âœ… Push the Docker image to the new ACR
          - task: Docker@2
            displayName: 'Push Docker Image to ACR'
            inputs:
              command: push
              containerRegistry: ''
              repository: $(acrLoginServer)/$(imageName)
              tags: $(imageTag)
              
          # âœ… Continue with the rest of your deployment steps (Key Vault, Container App, etc.)
          # ...
          - task: TerraformTaskV4@4
            displayName: 'Terraform Apply - All remaining resources'
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: terraform
              environmentServiceNameAzureRM: $(azureSubscription)
              commandOptions: -auto-approve

          - task: AzureCLI@2
            displayName: 'Show Terraform output (app_url)'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Terraform outputs:"
                terraform -chdir=terraform output || true