trigger:
  branches:
    include:
      - main

variables:
  acrName: 'contactsaveracr123'
  containerImage: 'contact-saver'
  dockerfilePath: 'backend/Dockerfile'
  tfBackendRg: 'yousma-rg'
  tfStorage: 'yousmastorage'
  tfContainer: 'tfstate'
  tfKey: 'terraform.tfstate'
  webAppName: 'contact-webapp-123'
  keyVaultName: 'contactkv123'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
    - job: BuildImage
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: Docker@2
          displayName: 'Build and Push to ACR'
          inputs:
            containerRegistry: 'acr-connection'
            repository: $(containerImage)
            command: buildAndPush
            Dockerfile: $(dockerfilePath)
            tags: |
              latest

- stage: Deploy
  displayName: 'Terraform Infra Deployment'
  dependsOn: Build
  jobs:
    - job: DeployTerraform
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: AzureCLI@2
          displayName: 'Run Terraform with Env Auth'
          inputs:
            azureSubscription: 'Azure-Yousma-Connection'
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              echo "Setting environment variables for SP authentication"
              export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
              export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
              export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
              export ARM_TENANT_ID=$(ARM_TENANT_ID)

              cd terraform

              echo "Running terraform init..."
              terraform init \
                -backend-config="resource_group_name=$(tfBackendRg)" \
                -backend-config="storage_account_name=$(tfStorage)" \
                -backend-config="container_name=$(tfContainer)" \
                -backend-config="key=$(tfKey)"

              echo "Getting ACR credentials"
              ACR_USERNAME=$(az acr credential show --name $(acrName) --query "username" -o tsv)
              ACR_PASSWORD=$(az acr credential show --name $(acrName) --query "passwords[0].value" -o tsv)

              echo "Running terraform apply..."
              terraform apply \
                -var="resource_group_name=$(tfBackendRg)" \
                -var="location=East US" \
                -var="acr_name=$(acrName)" \
                -var="app_service_plan_name=contact-asp" \
                -var="web_app_name=$(webAppName)" \
                -var="key_vault_name=$(keyVaultName)" \
                -var="email_api_key=sample-api-key" \
                -var="acr_admin_username=$ACR_USERNAME" \
                -var="acr_admin_password=$ACR_PASSWORD" \
                -var="container_image=$(containerImage)" \
                -auto-approve
