trigger:
  branches:
    include:
      - main

variables:
  azureServiceConnection: 'Azure-Yousma-Connection'
  dockerRegistryServiceConnection: 'acr-connection'
  acrName: 'contactsaveracr123'
  containerImage: 'contact-saver'
  dockerfilePath: 'backend/Dockerfile'
  tfBackendRg: 'yousma-rg'
  tfStorage: 'yousmastorage'
  tfContainer: 'tfstate'
  tfKey: 'terraform.tfstate'
  webAppName: 'contact-webapp-123'
  keyVaultName: 'contactkv123'

stages:

# -------------------- STAGE 1: Build & Push Docker Image --------------------
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
    - job: BuildImage
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: Docker@2
          displayName: 'Build and Push to ACR'
          inputs:
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(containerImage)
            command: buildAndPush
            Dockerfile: $(dockerfilePath)
            tags: |
              latest

# -------------------- STAGE 2: Deploy Infrastructure --------------------
- stage: Deploy
  displayName: 'Deploy Terraform Infrastructure and App'
  dependsOn: Build
  jobs:
    - job: Terraform
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: TerraformInstaller@0
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: '1.7.5'

        # ✅ Get ACR Admin Credentials
        - task: AzureCLI@2
          displayName: 'Get ACR Admin Credentials'
          inputs:
            azureSubscription: $(azureServiceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              ACR_USERNAME=$(az acr credential show --name $(acrName) --query "username" -o tsv)
              ACR_PASSWORD=$(az acr credential show --name $(acrName) --query "passwords[0].value" -o tsv)

              echo "##vso[task.setvariable variable=ACR_USERNAME]$ACR_USERNAME"
              echo "##vso[task.setvariable variable=ACR_PASSWORD]$ACR_PASSWORD"

        # ✅ Terraform Init via Azure CLI (no arm_client_id errors)
        - task: AzureCLI@2
          displayName: 'Terraform Init'
          inputs:
            azureSubscription: $(azureServiceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            workingDirectory: 'terraform'
            inlineScript: |
              terraform init \
                -backend-config="resource_group_name=$(tfBackendRg)" \
                -backend-config="storage_account_name=$(tfStorage)" \
                -backend-config="container_name=$(tfContainer)" \
                -backend-config="key=$(tfKey)"

        # ✅ Terraform Apply via CLI
        - task: AzureCLI@2
          displayName: 'Terraform Apply'
          inputs:
            azureSubscription: $(azureServiceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            workingDirectory: 'terraform'
            inlineScript: |
              terraform apply \
                -var="resource_group_name=$(tfBackendRg)" \
                -var="location=East US" \
                -var="acr_name=$(acrName)" \
                -var="app_service_plan_name=contact-asp" \
                -var="web_app_name=$(webAppName)" \
                -var="key_vault_name=$(keyVaultName)" \
                -var="email_api_key=sample-api-key" \
                -var="acr_admin_username=$(ACR_USERNAME)" \
                -var="acr_admin_password=$(ACR_PASSWORD)" \
                -var="container_image=$(containerImage)" \
                -auto-approve
