trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'Azure-Yousma-Connection'  # Your ARM connection
  containerRegistry: 'acr-connection1'          # Your Docker registry connection
  acrLoginServer: 'myprojectacr1234.azurecr.io'
  imageName: 'myapp'

stages:
- stage: CI
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: '$(imageName)'
        dockerfile: 'backend/Dockerfile'
        containerRegistry: '$(containerRegistry)'
        tags: |
          latest

- stage: CD
  displayName: 'Deploy Infra & App via Terraform'
  dependsOn: CI
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform 1.6.6'
      inputs:
        terraformVersion: '1.6.6'

    - script: terraform version
      displayName: 'Show Terraform Version'
      workingDirectory: 'terraform'

    - task: TerraformTaskV4@4
      name: TerraformInit
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'terraform'
        backendServiceArm: '$(azureSubscription)'
        backendAzureRmResourceGroupName: 'yousma-rg'
        backendAzureRmStorageAccountName: 'yousmastorage'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'
        environmentServiceNameAzureRM: '$(azureSubscription)'
        commandOptions: '-upgrade'  # ✅ Ensures azurerm >= 3.75.0 is installed

    - task: TerraformTaskV4@4
      name: TerraformApply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'terraform'
        environmentServiceNameAzureRM: '$(azureSubscription)'
